CREATE DATABASE carros;
USE carros;
CREATE TABLE carro (
  id INT(11) NOT NULL AUTO_INCREMENT,
  nome VARCHAR(45) NOT NULL,
  modelo VARCHAR(45) NOT NULL,
  ano YEAR NOT NULL,
  cor VARCHAR(10) NOT NULL,
  PRIMARY KEY (id)
);
